// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Menu struct {
	ID    string `json:"id"`
	Name  string `json:"name"`
	Price int    `json:"price"`
	Type  string `json:"type"`
}

type NewMenu struct {
	Name  string `json:"name"`
	Price int    `json:"price"`
	Type  string `json:"type"`
}
